export const GET_BATTLES= 'GET_BATTLES';
export const SEARCH_BATTLE='SEARCH_BATTLE';
export const SET_CURRENT="SET_CURRENT";
export const GET_LOCATION="GET_LOCATION";
export const GET_FILTER_LOCATION="GET_FILTER_LOCATION";
export const CLEAR_FILTER_LOCATION="CLEAR_FILTER_LOCATION";